version: 2

project_name: stream-share

builds:
  - binary: stream-share
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    goos:
      - windows
      - darwin
      - linux

    goarch:
      - amd64
      - arm64

archives:
  -
   format_overrides:
     - goos: windows
       format: zip

release:
  github:
    owner: x3n0n10
    name: stream-share
  draft: false

nfpms:
  -
   vendor: x3n0n10
   homepage: https://github.com/x3n0n10/stream-share
   maintainer: x3n0n10
   description: IPTV Proxy with LDAP support
   license: GPL-3.0
   formats:
     - deb
     - rpm

dockers:
  - image_templates:
    - "ghcr.io/x3n0n10/stream-share:{{ .Tag }}-arm64"
    - "ghcr.io/x3n0n10/stream-share:latest-arm64"
    - "x3n0n10/stream-share:{{ .Tag }}-arm64"
    - "x3n0n10/stream-share:latest-arm64"
    use: buildx
    goos: linux
    goarch: arm64
    ids:
    - stream-share
    build_flag_templates:
    - "--platform=linux/arm64/v8"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false
    dockerfile: .Dockerfile.goreleaser

  - image_templates:
    - "ghcr.io/x3n0n10/stream-share:{{ .Tag }}-amd64"
    - "ghcr.io/x3n0n10/stream-share:latest-amd64"
    - "x3n0n10/stream-share:{{ .Tag }}-amd64"
    - "x3n0n10/stream-share:latest-amd64"
    use: buildx
    goos: linux
    goarch: amd64
    ids:
    - stream-share
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false
    dockerfile: .Dockerfile.goreleaser

docker_manifests:
  - name_template: "x3n0n10/stream-share:{{ .Tag }}"
    image_templates:
      - "x3n0n10/stream-share:{{ .Tag }}-amd64"
      - "x3n0n10/stream-share:{{ .Tag }}-arm64"
  - name_template: "x3n0n10/stream-share:latest"
    image_templates:
      - "x3n0n10/stream-share:latest-amd64"
      - "x3n0n10/stream-share:latest-arm64"
  - name_template: "ghcr.io/x3n0n10/stream-share:{{ .Tag }}"
    image_templates:
      - "ghcr.io/x3n0n10/stream-share:{{ .Tag }}-amd64"
      - "ghcr.io/x3n0n10/stream-share:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/x3n0n10/stream-share:latest"
    image_templates:
      - "ghcr.io/x3n0n10/stream-share:latest-amd64"
      - "ghcr.io/x3n0n10/stream-share:latest-arm64"
