version: 2

project_name: stream-share

builds:
  - binary: stream-share
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    goos:
      - windows
      - darwin
      - linux

    goarch:
      - amd64
      - arm64

archives:
  -
   format_overrides:
     - goos: windows
       formats: [ 'zip' ]

release:
  github:
    owner: lucasduport
    name: stream-share
  draft: false

nfpms:
  -
   vendor: lucasduport
   homepage: https://github.com/lucasduport/stream-share
   maintainer: lucasduport
   description: IPTV Proxy with LDAP support
   license: GPL-3.0
   formats:
     - deb
     - rpm

dockers:
  - image_templates:
    - "ghcr.io/lucasduport/stream-share:{{ .Tag }}-arm64"
    - "{{ if not .Prerelease }}ghcr.io/lucasduport/stream-share:latest-arm64{{ end }}"
    - "lucasduport/stream-share:{{ .Tag }}-arm64"
    - "{{ if not .Prerelease }}lucasduport/stream-share:latest-arm64{{ end }}"
    use: buildx
    goos: linux
    goarch: arm64
    ids:
    - stream-share
    build_flag_templates:
    - "--platform=linux/arm64/v8"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false
    dockerfile: .Dockerfile.goreleaser

  - image_templates:
    - "ghcr.io/lucasduport/stream-share:{{ .Tag }}-amd64"
    - "{{ if not .Prerelease }}ghcr.io/lucasduport/stream-share:latest-amd64{{ end }}"
    - "lucasduport/stream-share:{{ .Tag }}-amd64"
    - "{{ if not .Prerelease }}lucasduport/stream-share:latest-amd64{{ end }}"
    use: buildx
    goos: linux
    goarch: amd64
    ids:
    - stream-share
    build_flag_templates:
    - "--platform=linux/amd64"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    skip_push: false
    dockerfile: .Dockerfile.goreleaser

docker_manifests:
  - name_template: "lucasduport/stream-share:{{ .Tag }}"
    image_templates:
      - "lucasduport/stream-share:{{ .Tag }}-amd64"
      - "lucasduport/stream-share:{{ .Tag }}-arm64"
  - name_template: "{{ if not .Prerelease }}lucasduport/stream-share:latest{{ end }}"
    image_templates:
      - "lucasduport/stream-share:latest-amd64"
      - "lucasduport/stream-share:latest-arm64"
    skip_push: "{{ if .Prerelease }}true{{ end }}"
  - name_template: "ghcr.io/lucasduport/stream-share:{{ .Tag }}"
    image_templates:
      - "ghcr.io/lucasduport/stream-share:{{ .Tag }}-amd64"
      - "ghcr.io/lucasduport/stream-share:{{ .Tag }}-arm64"
  - name_template: "{{ if not .Prerelease }}ghcr.io/lucasduport/stream-share:latest{{ end }}"
    image_templates:
      - "ghcr.io/lucasduport/stream-share:latest-amd64"
      - "ghcr.io/lucasduport/stream-share:latest-arm64"
    skip_push: "{{ if .Prerelease }}true{{ end }}"
